### Initialization

In [1]:
# For Colab only!

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [1]:
import tensorflow as tf

In [2]:
import torch

In [4]:
print(tf.__version__)
print(tf.test.is_gpu_available())

2.0.0
False


In [5]:
print(torch.__version__)
print(torch.cuda.is_available())

1.4.0
False


### Scalar Vector and Tensor

In [6]:
#  dim = 0 
a = tf.constant(2.4)
print(a.shape)
print(len(a.shape))
print(a)

# dim = 1 
a = tf.constant([2.4])
print(a)
print("dim = ",len(a.shape))

# dim = 2
b = tf.constant([[1,2],[3,4]])
print(b)
print("dim = ",len(b.shape))

c = tf.constant([[[1,2],[3,4]]])
print(c)
print("dim = ",len(c.shape))

d = tf.constant([[[1],[2]],[[3],[4]]])
print(d)
print("dim = ",len(d.shape))


()
0
tf.Tensor(2.4, shape=(), dtype=float32)
tf.Tensor([2.4], shape=(1,), dtype=float32)
dim =  1
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
dim =  2
tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)
dim =  3
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
dim =  3


In [7]:
#  dim = 0 
a = torch.tensor(2.4)
print(a.shape)
print(len(a.shape))
print(a)

# dim = 1 
a = torch.tensor([2.4])
print(a)
print("dim = ",len(a.shape))

# dim = 2
b = torch.tensor([[1,2],[3,4]])
print(b)
print("dim = ",len(b.shape))

c = torch.tensor([[[1,2],[3,4]]])
print(c)
print("dim = ",len(c.shape))

d = torch.tensor([[[1],[2]],[[3],[4]]])
print(d)
print("dim = ",len(d.shape))


torch.Size([])
0
tensor(2.4000)
tensor([2.4000])
dim =  1
tensor([[1, 2],
        [3, 4]])
dim =  2
tensor([[[1, 2],
         [3, 4]]])
dim =  3
tensor([[[1],
         [2]],

        [[3],
         [4]]])
dim =  3


* A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor.

* A torch.Tensor can initialize tensor with certain shape. But this is not a recommded initialization methode

In [8]:
#  dim = 0 
a = tf.Variable(2.4)
print(a.shape)
print(len(a.shape))
print(a)

# dim = 1 
a = tf.Variable([2.4])
print(a)
print("dim = ",len(a.shape))

# dim = 2
b = tf.Variable([[1,2],[3,4]])
print(b)
print("dim = ",len(b.shape))

c = tf.Variable([[[1,2],[3,4]]])
print(c)
print("dim = ",len(c.shape))

d = tf.Variable([[[1],[2]],[[3],[4]]])
print(d)
print("dim = ",len(d.shape))

()
0
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.4>
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.4], dtype=float32)>
dim =  1
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
dim =  2
<tf.Variable 'Variable:0' shape=(1, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>
dim =  3
<tf.Variable 'Variable:0' shape=(2, 2, 1) dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>
dim =  3


In [6]:
# dim = 1
# x = torch.Tensor(1)

print(x)
print('dim = ', len(x.shape))


# dim = 2
x = torch.IntTensor(2,3)
print(x)
print('dim = ', len(x.shape))

# dim = 3
x = torch.FloatTensor(2,3,4)
print(x)
print(x.shape)
print('dim = ', len(x.shape))

x = torch.empty(2,3,4)
print(x)
print(x.shape)
print('dim = ', len(x.shape))

tensor([4.9886e-15])
dim =  1
tensor([[         6,          0, 1167094992],
        [         1,          0,          0]], dtype=torch.int32)
dim =  2
tensor([[[2.9427e-44, 0.0000e+00, 9.4344e+35, 4.5898e-41],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.8101e+33, 4.5898e-41]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.8101e+33, 4.5898e-41, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00,        nan,        nan]]])
torch.Size([2, 3, 4])
dim =  3
tensor([[[1.6816e-44, 6.8247e-06, 0.0000e+00, 5.9062e+04],
         [0.0000e+00, 1.7165e-05, 0.0000e+00, 2.7432e+04],
         [0.0000e+00, 1.7165e-05, 0.0000e+00, 2.7432e+04]],

        [[0.0000e+00, 1.7165e-05, 1.4013e-45, 4.5918e-40],
         [4.6200e+03, 1.4013e-45, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.0000e+00]]])
torch.Size([2, 3, 4])
dim =  3


### Tensor Initialization
* From numpy or list
* All one/zero/eye
* Random normal/uniform

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
aa = tf.Variable(a)
print(aa)

# back to numpy, list and item
print(aa.numpy())
print(aa.numpy().tolist())

b = tf.ones(shape=[3,3])
print(b)

c = tf.zeros(shape=[1,2,3])
print(c)

d = tf.eye(4)
print(d)

e = tf.random.uniform([3,3],
                     minval=-1,
                     maxval= 1)
print(e)

f = tf.random.normal([3,3])
print(f)

g = tf.fill(dims=[3,3], value=3)
print(g)
print(g.shape)


<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([1, 2, 3])>
[1 2 3]
[1, 2, 3]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-0.92840195 -0.21091819 -0.2701943 ]
 [ 0.83940816  0.4870708   0.313586  ]
 [ 0.8899615   0.62667656 -0.33387423]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.00574434 -1.873318   -0.187527  ]
 [ 0.36099178 -0.87048984  0.36814544]
 [ 0.47805578 -0.08826071 -1.377957  ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)
(3, 3)


In [18]:
a = np.array([1,2,3])
aa = torch.from_numpy(a)
aa = torch.tensor(a)
print(aa)

# back to numpy, list, item
print(aa.numpy())
print(aa.tolist())
print(aa[0].item())

b = torch.ones([3,3])
print(b)

c = torch.zeros([1,2,3])
print(c)

d = torch.eye(4)
print(d)

e = torch.rand([3,3]) *2 -1
print(e)

f = torch.empty(3,3)
f = f.normal_()
print(f)

f = torch.tensor(np.random.normal( size= [3,3]))
print(f)

g = torch.rand_like(e)
print(g)

h = torch.full([3,3],fill_value = 3)
print(h)
print(h.shape)

tensor([[-0.2205,  1.1558, -1.1998],
        [ 0.5872, -0.1655, -0.8753],
        [-0.6385,  0.3930, -0.9416]])


### Indexing and slicing

start : end: step (end is not included)

In [13]:
x = tf.random.uniform([2,28,28,3])

print(x[0][0][0])
print(x[0,0,0])
print(x[0,0,0,:])

print(x[0,:,0,0].shape)

print(x[1,::2,::2,1].shape)

print(x[0,...,0].shape)

tf.Tensor([0.16387904 0.4265666  0.5988269 ], shape=(3,), dtype=float32)
tf.Tensor([0.16387904 0.4265666  0.5988269 ], shape=(3,), dtype=float32)
tf.Tensor([0.16387904 0.4265666  0.5988269 ], shape=(3,), dtype=float32)
(28,)
(14, 14)
(28, 28)


In [14]:
x = torch.rand([2,3,28,28])
print(x[0][0][0])
print(x[0,0,0])
print(x[0,0,0,:].shape)

print(x[0,1,::2,::2].shape)

print(x[0,...,0].shape)

tensor([0.6419, 0.2041, 0.1747, 0.9867, 0.2958, 0.4511, 0.1343, 0.1190, 0.1462,
        0.6560, 0.7630, 0.1408, 0.6491, 0.4121, 0.7311, 0.5382, 0.1502, 0.2961,
        0.7076, 0.5014, 0.8862, 0.9230, 0.0037, 0.2196, 0.5322, 0.4499, 0.2151,
        0.9921])
tensor([0.6419, 0.2041, 0.1747, 0.9867, 0.2958, 0.4511, 0.1343, 0.1190, 0.1462,
        0.6560, 0.7630, 0.1408, 0.6491, 0.4121, 0.7311, 0.5382, 0.1502, 0.2961,
        0.7076, 0.5014, 0.8862, 0.9230, 0.0037, 0.2196, 0.5322, 0.4499, 0.2151,
        0.9921])
torch.Size([28])
torch.Size([14, 14])
torch.Size([3, 28])


### Reshape

Image shape: [b, w, h, c] or [b, c, w, h]

Reshape, Squeeze, Unsqueeze, Transpose

In [15]:
x = tf.random.uniform([5,28,28,3])

print(tf.reshape(x, [5, 28*28, 3]).shape)
print(tf.reshape(x, [5, 14, 56, 3]).shape)

print(x.shape)

print(tf.expand_dims(x, axis=0).shape)

y = tf.expand_dims(x, axis=2)
print('y shape: ',y.shape)
print(tf.squeeze(y, axis=2).shape)

# Change dim [b,w,h,c] -> [b,c,w,h]

z = tf.transpose(x,perm=[0,3,1,2])
print('z shape', z.shape)

print(x.shape)


(5, 784, 3)
(5, 14, 56, 3)
(5, 28, 28, 3)
(1, 5, 28, 28, 3)
y shape:  (5, 28, 1, 28, 3)
(5, 28, 28, 3)
z shape (5, 3, 28, 28)
(5, 28, 28, 3)


In [16]:
x = torch.rand([5,3,28,28])

print(x.view(5,3,28*28).shape)
print(x.reshape(5,3,28*28).shape)
print(torch.reshape(x,[5,3,28*28]).shape)

print(x.reshape(5,3,14,56).shape)

y = x.unsqueeze(2)
print('y shape: ', y.shape)

print(y.squeeze(2).shape)

# exchange dim [b, c, w, h] -> [b, w, h, c]
z = x.transpose(1, 2).transpose(2, 3)
print('z shape: ', z.shape)

print(torch.transpose(x, 1,2).shape)
print(x.permute(0,3,1,2).shape)

print(x.shape)

torch.Size([5, 3, 784])
torch.Size([5, 3, 784])
torch.Size([5, 3, 784])
torch.Size([5, 3, 14, 56])
y shape:  torch.Size([5, 3, 1, 28, 28])
torch.Size([5, 3, 28, 28])
z shape:  torch.Size([5, 28, 28, 3])
torch.Size([5, 28, 3, 28])
torch.Size([5, 28, 3, 28])
torch.Size([5, 3, 28, 28])


### Broadcasting

Manully broadcast with `tf.broadcast_to` / `y.expand(*size)`.

Automatic broadcast in calculation.


In [17]:
x = tf.random.uniform([4,28,28,3])
y = tf.random.uniform([1,28,1,1])

print((tf.broadcast_to(y,[4,28,28,3])).shape)

print((x+y).shape)

(4, 28, 28, 3)
(4, 28, 28, 3)


In [18]:
x = torch.rand([4,3,28,28])
y = torch.rand([1,1,28,1])

print(y.expand(4,3,28,28).shape)

print((x+y).shape)

torch.Size([4, 3, 28, 28])
torch.Size([4, 3, 28, 28])


In [19]:
x = tf.random.uniform([4,28,28,3])
y = tf.random.uniform([4,28,1,1])

print((x + y).shape)

(4, 28, 28, 3)


### Merge and Split

* tf.concat 
* tf.split
* tf.stack
* tf.unstack

* Cat
* Stack
* Split
* Chunk

In [34]:
# Example [classes, students, scores] 
# Concat dim = 0, 

a = tf.random.uniform([4,32,8])
b = tf.random.uniform([5,32,8])
print(tf.concat([a,b], axis=0).shape)

# Concat dim = 1, Same classes different students
a = tf.random.uniform([4,10,8])
b = tf.random.uniform([4,22,8])
print(tf.concat([a,b], axis=1).shape)

#Concat dim = 2, Same classes, students, different subjects
a = tf.random.uniform([4,32,5])
b = tf.random.uniform([4,32,3])
print(tf.concat([a,b], axis=2).shape)

c = tf.random.uniform([9,32,8])

c1, c2 = tf.split(c,[3,6],axis=0)
print(c1.shape, c2.shape)


c1, c2, c3 = tf.split(c,3,axis=0)
print(c1.shape, c2.shape, c3.shape)

d1, d2, d3 = tf.unstack(c1,axis=0)
print(d1.shape, d2.shape, d3.shape)

print(tf.stack([d1,d2,d3], axis=0).shape)
print(tf.stack([c1,c2,c3], axis=0).shape)

# Example [classes, students, scores] -> [grades, classes, students, scores]
a = tf.random.uniform([4,32,8])
b = tf.random.uniform([4,32,8])
print(tf.stack([a,b], axis=0).shape)

(9, 32, 8)
(4, 32, 8)
(4, 32, 8)
(3, 32, 8) (6, 32, 8)
(3, 32, 8) (3, 32, 8) (3, 32, 8)
(32, 8) (32, 8) (32, 8)
(3, 32, 8)
(3, 3, 32, 8)
(2, 4, 32, 8)


In [35]:
# Example [classes, students, scores] 
# Concat dim = 0, 

a = torch.rand(4,32,8)
b = torch.rand(5,32,8)
print(torch.cat([a,b], dim=0).shape)

# Concat dim = 1, Same classes different students
a = torch.rand(4,10,8)
b = torch.rand(4,22,8)
print(torch.cat([a,b], dim=1).shape)

#Concat dim = 2, Same classes, students, different subjects
a = torch.rand(4,32,5)
b = torch.rand(4,32,3)
print(torch.cat([a,b], dim=2).shape)


c = torch.rand(9,32,8)
# c1, c2 = torch.split(c,[3,6],dim=0)
c1, c2 = c.split([3,6],dim=0)
print(c1.shape, c2.shape)

# c1, c2, c3 = torch.split(c,3,dim=0)
c1, c2, c3 = c.split(3,dim=0)
print(c1.shape, c2.shape, c3.shape)

# c1, c2, c3 = torch.chunk(c,3,dim=0)
c1, c2, c3 = c.chunk(3,dim=0)
print(c1.shape, c2.shape, c3.shape)


# Example [classes, students, scores] -> [grades, classes, students, scores]
a = torch.rand(4,32,8)
b = torch.rand(4,32,8)
print(torch.stack([a,b],dim=0).shape)

torch.Size([9, 32, 8])
torch.Size([4, 32, 8])
torch.Size([4, 32, 8])
torch.Size([3, 32, 8]) torch.Size([6, 32, 8])
torch.Size([3, 32, 8]) torch.Size([3, 32, 8]) torch.Size([3, 32, 8])
torch.Size([3, 32, 8]) torch.Size([3, 32, 8]) torch.Size([3, 32, 8])
torch.Size([2, 4, 32, 8])
