### Initialization

In [1]:
# For Colab only!

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [1]:
import tensorflow as tf

In [2]:
import torch

In [3]:
print(tf.__version__)
print(tf.test.is_gpu_available())

2.1.0
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
True


In [4]:
print(torch.__version__)
print(torch.cuda.is_available())

1.4.0
True


### Basic

elementwise

**"  + - * /  "**



In [5]:
#  "+ - * /"
#  add subtract multiply div
a = tf.random.uniform([3,4])
b = tf.random.uniform([4])

print(a+b)
print(tf.add(a,b).shape)

print(a-b)
print(tf.subtract(a,b).shape)

print(a*b)
print(tf.multiply(a,b).shape)

print(a/b)
print(tf.divide(a,b).shape)

tf.Tensor(
[[1.2716367 1.8942944 0.703163  0.8952806]
 [1.2450049 1.2213507 1.1603341 0.7730472]
 [0.9520465 1.680704  0.5407109 0.9664177]], shape=(3, 4), dtype=float32)
(3, 4)
tf.Tensor(
[[-0.6214237  -0.04250443 -0.32829726 -0.61047864]
 [-0.64805555 -0.71544814  0.12887383 -0.73271203]
 [-0.94101393 -0.2560948  -0.49074936 -0.53934157]], shape=(3, 4), dtype=float32)
(3, 4)
tf.Tensor(
[[0.30772313 0.8966361  0.09666479 0.10721079]
 [0.2825153  0.24495785 0.3324417  0.01518377]
 [0.00522134 0.6897953  0.01288334 0.16076845]], shape=(3, 4), dtype=float32)
(3, 4)
tf.Tensor(
[[0.34347185 0.95610857 0.36343208 0.18914177]
 [0.3153356  0.26120552 1.2498862  0.02678727]
 [0.00582791 0.7355484  0.0484377  0.2836284 ]], shape=(3, 4), dtype=float32)
(3, 4)


In [6]:
#  "+ - * /"
#  add sub mul div
a = torch.rand(3,4)
b = torch.rand(4)

print(a+b)
print(torch.add(a,b).shape)

print(a-b)
print(torch.sub(a,b).shape)

print(a*b)
print(torch.mul(a,b).shape)

print(a/b)
print(torch.div(a,b).shape)

tensor([[0.7799, 0.8954, 1.6239, 0.4891],
        [0.1286, 0.7415, 1.5803, 0.7019],
        [0.6216, 1.2015, 1.6686, 0.7317]])
torch.Size([3, 4])
tensor([[ 0.6811,  0.4708, -0.3122,  0.4146],
        [ 0.0298,  0.3170, -0.3558,  0.6275],
        [ 0.5227,  0.7769, -0.2675,  0.6572]])
torch.Size([3, 4])
tensor([[0.0361, 0.1450, 0.6349, 0.0168],
        [0.0039, 0.1124, 0.5927, 0.0247],
        [0.0283, 0.2100, 0.6781, 0.0259]])
torch.Size([3, 4])
tensor([[14.7841,  3.2177,  0.6775, 12.1368],
        [ 1.6028,  2.4930,  0.6325, 17.8541],
        [11.5792,  4.6597,  0.7236, 18.6536]])
torch.Size([3, 4])


### MatMul
1. @
2. matmul


In [7]:
a = tf.random.uniform([3,4])
b = tf.random.uniform([4,3])

print(a@b)
print(tf.matmul(a,b))

# Example: image x [2, 784] -> [2, 256]
# w: [in, out]
# b: [out]

x = tf.random.uniform([2,784])
w = tf.random.uniform([784,256])
b = tf.zeros([256])

out = x@w + b
print(out.shape)

tf.Tensor(
[[1.0291786  0.7188834  0.77422404]
 [1.566424   0.9554346  1.0769386 ]
 [1.9096622  1.3246509  1.5444131 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.0291786  0.7188834  0.77422404]
 [1.566424   0.9554346  1.0769386 ]
 [1.9096622  1.3246509  1.5444131 ]], shape=(3, 3), dtype=float32)
(2, 256)


In [8]:
a = torch.rand(3,4)
b = torch.rand(4,3)

print(a@b)
print(torch.matmul(a,b))

# Example: image x [2, 784] -> [2, 256]
# w: [out, in],  w.t() transpose 
# b: [out]

x = torch.rand(2, 784)
w = torch.rand(256, 784)
b = torch.zeros(256)

out = x@w.t() + b
print(out.shape)

tensor([[0.8665, 0.8029, 1.3531],
        [0.7052, 0.8495, 1.0810],
        [0.8507, 0.6912, 1.3413]])
tensor([[0.8665, 0.8029, 1.3531],
        [0.7052, 0.8495, 1.0810],
        [0.8507, 0.6912, 1.3413]])
torch.Size([2, 256])


#### Dim over 2

Only MatMul the last two dimentions

In [9]:
a = tf.random.uniform([2,3,28,12])
b = tf.random.uniform([2,3,12,28])

print((a@b).shape)
print(tf.matmul(a,b).shape)

# automatic broadcasting
# c [12, 14] -> [1,1,12,14] ->[2,3,12,14]
c = tf.random.uniform([12,14])
print((a@c).shape)

(2, 3, 28, 28)
(2, 3, 28, 28)
(2, 3, 28, 14)


In [10]:
a = torch.rand(2,3,28,12)
b = torch.rand(2,3,12,28)

print((a@b).shape)
print(torch.matmul(a,b).shape)

# automatic broadcasting
# c [12, 14] -> [1,1,12,14] ->[2,3,12,14]
c = torch.rand(12,14)
print((a@c).shape)

torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 14])


### Power and log
elemente-wise: pow sqll **

In [11]:
a = tf.fill([3,3],9.0)
print(a**2)
print(tf.pow(a, 2))
print(a**0.5)
print(tf.sqrt(a))

b = tf.ones([3,3])*2
c = tf.exp(b)
d = tf.math.log(c)
print(b, c, d)

tf.Tensor(
[[81. 81. 81.]
 [81. 81. 81.]
 [81. 81. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[81. 81. 81.]
 [81. 81. 81.]
 [81. 81. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[7.389056 7.389056 7.389056]
 [7.389056 7.389056 7.389056]
 [7.389056 7.389056 7.389056]], shape=(3, 3), dtype=float32) tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float32)


In [12]:
a = torch.full([3,3],9)
print(a**2)
print(torch.pow(a,2))
print(a**0.5)
print(torch.sqrt(a))

b = torch.ones([3,3])*2
c = torch.exp(b)
d = torch.log(c)
print(b, c, d)

tensor([[81., 81., 81.],
        [81., 81., 81.],
        [81., 81., 81.]])
tensor([[81., 81., 81.],
        [81., 81., 81.],
        [81., 81., 81.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) tensor([[7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891]]) tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


### Approximation

* floor() ceil()
* round()
* trunc() frac()

In [13]:
import numpy as np

In [14]:
a = tf.constant(3.14)
print(tf.floor(a))
print(tf.math.ceil(a))
print(tf.math.round(a))
print(np.trunc(a.numpy()))
print(np.modf(a.numpy())[0])

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
3.0
0.1400001


In [15]:
a = torch.tensor(3.14)
print(a.floor())
print(a.ceil())
print(a.round())
print(a.trunc())
print(a.frac())

tensor(3.)
tensor(4.)
tensor(3.)
tensor(3.)
tensor(0.1400)


### Statistics
* norm
* mean sum
* prod
* max, min, argmin, argmax ▪ kthvalue, topk

In [78]:
a = tf.fill([8], 1)
a = tf.cast(a, tf.float64)
b = tf.reshape(a, [2,4])
c = tf.reshape(a, [2,2,2])

print(b)
print(c)

print(tf.norm(b,ord=1).numpy())
print(tf.norm(b,ord=2).numpy())
print(tf.norm(b,ord=2, axis=0))

a = tf.constant(np.arange(8))
a = tf.reshape(a,[2,4])
print(a)

print(tf.reduce_min(a))
print(tf.reduce_mean(a))
print(tf.reduce_max(a))
print(tf.reduce_prod(a))
print(tf.reduce_sum(a))
print(tf.argmax(a, 0))
print(tf.argmin(a, 0))

# Example: x is the output of 4 MINST images
x = tf.random.uniform([4,10])
print(tf.argmax(x,1))
print(tf.reduce_max(x, axis=1))
print(tf.reduce_max(x, axis=1, keepdims=True))

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float64)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float64)
8.0
2.8284271247461903
tf.Tensor([1.41421356 1.41421356 1.41421356 1.41421356], shape=(4,), dtype=float64)
tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(28, shape=(), dtype=int64)
tf.Tensor([1 1 1 1], shape=(4,), dtype=int64)
tf.Tensor([0 0 0 0], shape=(4,), dtype=int64)
tf.Tensor([5 0 3 1], shape=(4,), dtype=int64)
tf.Tensor([0.9082575  0.93621755 0.9435929  0.9036423 ], shape=(4,), dtype=float32)
tf.Tensor(
[[0.9082575 ]
 [0.93621755]
 [0.9435929 ]
 [0.9036423 ]], shape=(4, 1), dtype=float32)


In [86]:
a = torch.full([8], 1)
b = a.reshape([2,4])
c = a.reshape([2,2,2])

print(b)
print(c)

# torch.norm()
print(b.norm(1))
print(c.norm(2))

print(b.norm(1, dim = 0))
print(b.norm(2, dim = 1))

print(c.norm(1, dim = 0))
print(c.norm(2, dim = 1))
print(c.norm(2, dim = 2).shape)

a = torch.arange(8).reshape(2,4).float()
print(a)
print(a.min(), a.max(), a.mean(), a.prod())
print(a.sum())
print(a.argmax(), a.argmin())
# torch.argmax()
print(a.argmax(dim=0), a.argmax(dim=1))

# Example: x is the output of 4 MINST images
x = torch.rand(4,10)
print(x.argmax(dim=1))
print(x.max(dim =1))
print(x.max(dim=1, keepdim=True))
# torch.topk()
# torch.kthvalue()
print(x.topk(3,dim=1))
print(x.kthvalue(7,dim=1))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor(8.)
tensor(2.8284)
tensor([2., 2., 2., 2.])
tensor([2., 2.])
tensor([[2., 2.],
        [2., 2.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
torch.Size([2, 2])
tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])
tensor(0.) tensor(7.) tensor(3.5000) tensor(0.)
tensor(28.)
tensor(7) tensor(0)
tensor([1, 1, 1, 1]) tensor([3, 3])
tensor([6, 8, 0, 1])
torch.return_types.max(
values=tensor([0.7343, 0.9775, 0.6649, 0.9459]),
indices=tensor([6, 8, 0, 1]))
torch.return_types.max(
values=tensor([[0.7343],
        [0.9775],
        [0.6649],
        [0.9459]]),
indices=tensor([[6],
        [8],
        [0],
        [1]]))
torch.return_types.topk(
values=tensor([[0.7343, 0.7134, 0.6342],
        [0.9775, 0.8714, 0.7993],
        [0.6649, 0.6179, 0.5973],
        [0.9459, 0.9299, 0.4478]]),
indices=tensor([[6, 8, 4],
        [8, 1, 5],
        [0, 1,

### Clamp


In [98]:
grad = tf.random.uniform([2,3], minval=15)

print(grad)

print(tf.reduce_max(grad))
print(tf.reduce_min(grad))

print(tf.clip_by_value(grad, 5,10))


tf.Tensor(
[[10.652033   5.9660015  2.4843903]
 [11.617971   3.1870842  5.1878815]], shape=(2, 3), dtype=float32)
tf.Tensor(11.617971, shape=(), dtype=float32)
tf.Tensor(2.4843903, shape=(), dtype=float32)
tf.Tensor(
[[10.         5.9660015  5.       ]
 [10.         5.         5.1878815]], shape=(2, 3), dtype=float32)


In [89]:
grad = torch.rand(2,3)*15

print(grad)

print(grad.max())
print(grad.min())

print(torch.clamp(grad, min=5, max=10))
print(grad.clamp(5,10))

tensor([[12.8346,  9.5469, 14.3791],
        [12.7299,  2.6548,  5.8642]])
tensor(14.3791)
tensor(2.6548)
tensor([[10.0000,  9.5469, 10.0000],
        [10.0000,  5.0000,  5.8642]])
tensor([[10.0000,  9.5469, 10.0000],
        [10.0000,  5.0000,  5.8642]])


### Compare

* > < == != >= <=
* equal



In [97]:
x = tf.random.uniform([4,10],minval=0,maxval=2)
print(x>1)

y = x
print(tf.equal(x,y))
print(x == y)
print(tf.eq(x,y))



tf.Tensor(
[[False  True False  True False  True  True  True False  True]
 [ True False  True  True False False  True False False  True]
 [ True False  True  True False False  True  True  True  True]
 [ True False False  True False  True False False False False]], shape=(4, 10), dtype=bool)
tf.Tensor(
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]], shape=(4, 10), dtype=bool)
tf.Tensor(
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]], shape=(4, 10), dtype=bool)


AttributeError: module 'tensorflow' has no attribute 'eq'

In [90]:
x = torch.rand([4,10])
print(x>1)

y = x

print(torch.eq(x,y))
print(x == y)
print(torch.equal(x,y))


tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])
tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])
True


In [19]:
x = tf.random.uniform([4,28,28,3])
y = tf.random.uniform([4,28,1,1])

print((x + y).shape)

(4, 28, 28, 3)
